{
 "title": "Solaris Node Exporter",
 "tags": [
  "solaris",
  "OS"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "ip",
    "query": "label_values(solaris_exporter_uptime_seconds_total,ip)"
   },
   { "name": "t", "label": "rate interval", "query": "2m,3m,4m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "All-System Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage % (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "ip",
   "yaxes": [
    { "format": "short", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "rate(solaris_exporter_cpu_time_total{ip=~\"${ip}\",statistic=~\"system|user|iowait\"}[$t]) / ignoring (statistic) group_left(vcpu) (solaris_exporter_cpu_load{ip=~\"${ip}\",statistic=\"vcpu\"} )",
     "legendFormat": "{{ip}}-{{statistic}}"
    }
   ]
  },
  {
   "title": "CPU load Average (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "repeat": "ip",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_cpu_load{ip=~\"${ip}\",statistic=~\"load.+|vcpu\"}",
     "legendFormat": "{{ip}}-{{statistic}}"
    }
   ]
  },
  {
   "title": "Memory stack (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "repeat": "ip",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_memory_usage_bytes{ip=~\"${ip}\",type=\"virtual\",counter=~\"available|used\"}",
     "legendFormat": "{{ip}}-{{counter}}"
    }
   ]
  },
  {
   "title": "Swap stack (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "repeat": "ip",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_memory_usage_bytes{ip=~\"${ip}\",type=\"swap\",counter=~\"free|used\"}",
     "legendFormat": "{{ip}}-{{counter}}"
    }
   ]
  },
  {
   "title": "Disk %busy (max among devs) (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit", "label": "percent" }
   ],
   "targets": [
    {
     "expr": "max by (ip)(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=~\"rtime\"}[${t}]))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Disk Service Time, ms (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s", "label": "msec" }
   ],
   "targets": [
    {
     "expr": "\nmax by (ip,driver) (sum by (name, admin_name, ip, admin_desc, driver) (rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=\"rlentime\"}[${t}]))\n/ ignoring (statistic,stat_desc) \nsum by (name, admin_name, ip, admin_desc, driver)\n(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=~\"reads|writes\"}[${t}])>1))",
     "legendFormat": "{{ip}}-driver-{{driver}}-Service-Time"
    },
    {
     "expr": "\nmax by (ip,driver) (sum by (name, admin_name, ip, admin_desc, driver) (rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=\"wlentime\"}[${t}]))\n/ ignoring (statistic,stat_desc) \nsum by (name, admin_name, ip, admin_desc, driver)\n(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=~\"reads|writes\"}[${t}])>1))",
     "legendFormat": "{{ip}}-driver-{{driver}}-Wait-Time"
    }
   ]
  },
  {
   "title": "Disk IOPS (by dev types) (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "cps", "label": "writes" }
   ],
   "targets": [
    {
     "expr": "sum by (statistic, ip, driver)(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=~\"reads|writes\"}[${t}]))",
     "legendFormat": "{{ip}}-sum-of-all-{{driver}}(driver)-devices-{{statistic}}"
    }
   ]
  },
  {
   "title": "Disk MBPS Summary (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "writes" }
   ],
   "targets": [
    {
     "expr": "sum by (statistic, ip, driver)(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=~\"nread|nwritten\"}[${t}]))",
     "legendFormat": "{{ip}}-sum-of-all-{{driver}}(driver)-devices-{{statistic}}"
    }
   ]
  },
  {
   "title": "Network Trafic (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(solaris_exporter_network_usage_total{ip=~\"${ip}\", statistic=~\"bytes_sent|bytes_recv\"}[${t}])*8",
     "legendFormat": "{{ip}}-{{NIC}}-{{statistic}}"
    }
   ]
  },
  {
   "title": "Network Errors (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(solaris_exporter_network_usage_total{ip=~\"${ip}\",statistic=~\"dropin|dropout|errin|errout\"}[${t}])",
     "legendFormat": "{{ip}}-{{NIC}}-{{statistic}}"
    }
   ]
  },
  {
   "title": "Swap IN / Swap OUT (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_memory_usage_bytes{ip=~\"${ip}\",type=\"swap\",counter=~\"sin|sout\"}",
     "legendFormat": "{{ip}}-{{counter}}"
    }
   ]
  },
  {
   "title": "Average transaction size per device over time period (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=\"nread\"}[${t}])>0)/ ignoring(statistic,stat_desc) (rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=\"reads\"}[${t}])>0)",
     "legendFormat": "{{ip}}-{{admin_name}}-reads"
    },
    {
     "expr": "(rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=\"nwritten\"}[${t}])>0)/ ignoring(statistic,stat_desc) (rate(solaris_exporter_diskio_usage_total{ip=~\"${ip}\",statistic=\"writes\"}[${t}])>0)",
     "legendFormat": "{{ip}}-{{admin_name}}-writes"
    }
   ]
  },
  {
   "title": "Disk Space Free bytes (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_diskspace_usage_bytes{ip=~\"${ip}\",fstype=~\"zfs|ufs\",statistic=\"free\"}",
     "legendFormat": "{{ip}} {{mountpoint}}  {{fstype}}  {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space %used (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_diskspace_usage_bytes{ip=~\"${ip}\",fstype=~\"zfs|ufs\",statistic=\"percent\"}",
     "legendFormat": "{{ip}} {{mountpoint}}  {{fstype}}  {{device}}  %used"
    }
   ]
  },
  {
   "title": "Avg trans sz/device (${ip}) (disabled queries)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ]
  },
  { "title": "Per-Zone Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Time ${ip}",
   "type": "graph",
   "description": "CPU time % by zones",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "repeat": "ip",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20, rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"user|kernel\"}[${t}]))",
     "legendFormat": "pset{{pset}}, zone:{{zone}}, {{statistic}}"
    }
   ]
  },
  {
   "title": "Thread Reads/Writes ${ip}",
   "type": "graph",
   "description": "Number of bytes of successful reads and writes by CPU threads. \nA read can occur through the read, readv or pread system calls.\nA write can occur through the write, writev, or pwrite system calls.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "repeat": "ip",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"readch|writech\"}[${t}]))",
     "legendFormat": "{{zone}} {{statistic}} ({{stat_desc}})"
    }
   ]
  },
  {
   "title": "Thread Reads/Writes ${ip}",
   "type": "graph",
   "description": "Number of successful reads and writes by CPU threads. \nA read can occur through the read, readv or pread system calls.\nA write can occur through the write, writev, or pwrite system calls.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "repeat": "ip",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"sysread|syswrite\"}[${t}]))",
     "legendFormat": "{{zone}} {{statistic}} ({{stat_desc}})"
    }
   ]
  },
  {
   "title": "CPU Time ${ip}",
   "type": "grafana-piechart-panel",
   "description": "CPU time % by psets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "repeat": "ip",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (pset) (sum without (statistic) (rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"user|kernel\"}[${t}])) *  ignoring(statistic,stat_desc) group_left solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=\"cpus\"})",
     "legendFormat": "pset{{pset}} used"
    },
    {
     "expr": "avg by (pset) (solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=\"cpus\"}) - sum by (pset) (sum without (statistic) (rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"user|kernel\"}[${t}])) *  ignoring(statistic,stat_desc) group_left solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=\"cpus\"})",
     "legendFormat": "pset{{pset}} idle"
    }
   ]
  },
  {
   "title": "CPU Time ${ip}",
   "type": "grafana-piechart-panel",
   "description": "CPU time % by zones",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "repeat": "ip",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum without (statistic) (rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"user|kernel\"}[${t}])) *  ignoring(statistic,stat_desc) group_left solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=\"cpus\"})",
     "legendFormat": "pset{{pset}} {{zone}} used"
    },
    {
     "expr": "avg by (pset) (solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=\"cpus\"}) - sum by (pset) (sum without (statistic) (rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=~\"user|kernel\"}[${t}])) *  ignoring(statistic,stat_desc) group_left solaris_exporter_per_zone_usage_total{ip=~\"${ip}\", statistic=\"cpus\"})",
     "legendFormat": "pset{{pset}} idle"
    }
   ]
  },
  {
   "title": "Virtual Memory usage, % ${ip}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "repeat": "ip",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, solaris_exporter_per_zone_caps_total{ip=~\"${ip}\", zone!=\"global\", statistic=~\"swap_usage.*\"} / ignoring (statistic) solaris_exporter_per_zone_caps_total{ip=~\"${ip}\", zone!=\"global\", statistic=~\"swap_limit.*\"} )",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "NProcs, ${ip}",
   "type": "graph",
   "description": "Number of running processed in zone",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "repeat": "ip",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, solaris_exporter_per_zone_caps_total{ip=~\"${ip}\", zone!=\"global\", statistic=~\"nprocs_.*\"})",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Thread system calls ${ip}",
   "type": "graph",
   "description": "System call that were madden in zones per time.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
   "repeat": "ip",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(solaris_exporter_per_zone_usage_total{ip=~\"${ip}\",statistic=~\"syscall|sysspawn|sysexec|sysfork\"}[${t}]))",
     "legendFormat": "{{zone}} {{statistic}} ({{stat_desc}})"
    }
   ]
  },
  { "title": "Exporter Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Dirty time diffirence between ${ip} and Prometheus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "abs(solaris_exporter_current_time_seconds_total{job=\"solaris_exporter\", ip=~\"${ip}\"}\n          - timestamp(solaris_exporter_current_time_seconds_total{job=\"solaris_exporter\", ip=~\"${ip}\"})\n          )",
     "legendFormat": "{{ip}}"
    },
    {}
   ]
  },
  {
   "title": "Solaris Workers Errors (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "cps", "label": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(solaris_exporter_diskio_usage_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-diskIO"
    },
    {
     "expr": "rate(solaris_exporter_network_usage_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-network"
    },
    {
     "expr": "rate(solaris_exporter_per_zone_cpu_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-per_zone_cpu"
    },
    {
     "expr": "rate(solaris_exporter_per_zone_caps_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-per_zone_caps"
    },
    {
     "expr": "rate(solaris_exporter_zpool_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-zpool"
    },
    {
     "expr": "rate(solaris_exporter_fmadm_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-fmadm"
    },
    {
     "expr": "rate(solaris_exporter_disk_error_collector_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-disk_error_collector"
    },
    {
     "expr": "rate(solaris_exporter_fc_paths_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-fc_paths_errors"
    },
    {
     "expr": "rate(solaris_exporter_svcs_x_errors_total{ip=~\"${ip}\"}[$t])",
     "legendFormat": "{{instance}}-svcs-x"
    }
   ]
  },
  {
   "title": "Scrape Duration from ${ip}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"solaris_exporter\", ip=~\"${ip}\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Solaris Workers Time (${ip})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "solaris_exporter_diskio_usage_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-diskIO"
    },
    {
     "expr": "solaris_exporter_cpu_load_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-cpu_load"
    },
    {
     "expr": "solaris_exporter_cpu_time_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-cpu_time"
    },
    {
     "expr": "solaris_exporter_MemCollector_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-Memory"
    },
    {
     "expr": "solaris_exporter_network_usage_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-network"
    },
    {
     "expr": "solaris_exporter_diskspace_worker{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-disk_space"
    },
    {
     "expr": "solaris_exporter_per_zone_cpu_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-per_zone_cpu"
    },
    {
     "expr": "solaris_exporter_per_zone_caps_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-per_zone_caps"
    },
    {
     "expr": "solaris_exporter_disk_errors_collector_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-diskErrors"
    },
    {
     "expr": "solaris_exporter_fc_paths_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-fc_paths"
    },
    {
     "expr": "solaris_exporter_svcs_x_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-svcs-x"
    },
    {
     "expr": "solaris_exporter_fmadm_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-fmadm"
    },
    {
     "expr": "solaris_exporter_zpool_processing{ip=~\"${ip}\"}",
     "legendFormat": "{{instance}}-zpool"
    },
    {
     "expr": "scrape_duration_seconds{ip=~\"${ip}\",job=\"by_ssh_db_cpu\"}",
     "legendFormat": "{{instance}}-by_ssh_db_cpu"
    }
   ]
  }
 ]
}